source "https://rubygems.org"

gem "base64"
gem "bigdecimal"
gem "csv"
gem "logger"
gem "ostruct"
gem "sass-embedded", "~> 1.69"
gem "jekyll", "4.3.3"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.16.5"
  gem 'jekyll-tagging', "1.1.0"
  gem "jekyll-sitemap", "1.4.0"
end
